---
title: "covid19census:  U.S. and Italy COVID-19 epidemiolagical data with demographic and health related metrics"
#date: "`r Sys.Date()`"
authors:
  - name: Claudio Zanettini
    email: claudio.zanettini@gmail.com
    address:  Department of Oncology, Johns Hopkins University School of Medicine, Baltimore, MD, USA
  - name: Luigi Marchionni
    email: marchion@jhu.edu
    address: Department of Oncology, Johns Hopkins University School of Medicine, Baltimore, MD, USA
    corresponding_author: yes
  - name: Others to be add
    email: otherst@example.com
    address: Another University

abstract: |
  This is the abstract.

  It consists of two paragraphs.
acknowledgements: |
  *Funding* : C.Z. and L.M.were supported by XXXX.

  It consists of two paragraphs.
keywords:
  - covid19
  - R

#fontsize: 12pt
#spacing: halfline # could also be oneline
#classoptions:
#  - endnotes
bibliography: mybibfile.bib
output: rticles::oup_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE) # By default, hide code; set to TRUE to see code
knitr::opts_chunk$set(fig.pos = 'p') # Places figures on their own pages
knitr::opts_chunk$set(out.width = '100%', dpi=300) # Figure resolution and size
knitr::opts_chunk$set(fig.env="figure") # Latex figure environment

library(xtable) # Creates tables that follow OUP guidelines; other options, such as kable, may also be workable
```

# Introduction

In the mist of a virus pandemic, unraveling the constant flow of epidemiological data is of paramount importance, not only to  guide the implementation and evaluation of non-pharmacological interventions, but also to optimize drug development. 

* Examples of epdidemiological alone or + dother data guiding interventions:  
[@kissler2020s]: proposed non pharmacological intervention

[@wu2020m]: correlation p2.5

[BCG](https://www.who.int/news-room/commentaries/detail/bacille-calmette-gu%C3%A9rin-(bcg)-vaccination-and-covid-19): clinical trial on BCG

**We need data banks, repositories of aggregated data**

* Examples of that and databanks of epidemiological as well as genetic data.
 [The traking project](https://covidtracking.com/)

* Examples of R package [ccdcovidview](https://feedly.com/i/entry/bdiQAD3fuPUMyDNqrmPKRt6BvYW45zeCOcg+AUEj5wM=_1716a5b8395:28a35fb:7f4666f4)


Boom our package


#  Alghorithm

A family of `get` functions is employed by the `R` package to extract updated time-series data dynamically from different on-line sources.

For **U.S** the prefix of the functions to extract data is `getus_`, and it is followed by the specific metric of interest:

  * `getus_covid`: extracts data of COVID-19 from the [New York Time git repository](https://github.com/nytimes/covid-19-data).
  * `getus_dex`: extracts data of DEX, an [activity indexes](https://github.com/COVIDExposureIndices/COVIDExposureIndices) calculated  by  Victor Couture, Jonathan Dingel, Allison Green, Jessie Handbury, and Kevin Williams based on smartphone movement data provided by `PlaceIQ`.
  * `getus_tests`: extract info regarding number of tests performed, their results and hospitalization from the repository of [the Covid Tracking Project](https://covidtracking.com/api}).
  * `getus_all`: executes all the above functions and join the results with other datasets statically contained in the package, and returns a `dataframe` with 304 variables.
  
Data regarding the household composition, population sex and age and poverty levels (2018), were retrieved from the [American Community Survey](https://data.census.gov/cedsci/table?q=United%20States). Medical conditions, tobacco use, cancer and, data relative to the number of medical and emergency visits (2017) of medicare beneficiaries were obtained from the [Mapping Medicare Disparities](https://data.cms.gov/mapping-medicare-disparities). The number of hospital beds per county (2020) was calculated from data of the  [Homeland Infrastructure Foundation](https://hifld-geoplatform.opendata.arcgis.com/datasets/hospitals/data?page=18).

For **Italy**, the prefix of the function is `getit_` followed by `covid` or `all`.

  * `getit_covid`: extracts data of COVID-19 cases, deaths, hospitalizations and tests from the [Protezione Civle]( "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv").
  * `getit_all`: executes the above function and join the results with other datasets statically contained in the package and returns a `dataframe` with 64 variables.
  
Age and sex of the population (2019),  first aid and medical guard visits (2018), smoking status (2018),  prevalence of chronic conditions (2018), annual-household income (2017), household crowding index (2018) and body-mass index were dataset collect by [ISTAT](http://dati.istat.it/?lang=en). Prevalence of types of cancer patients (2016), influenza-vaccination coverage (2019) and the number of hospital beds per 1000 people (2017) were obtained from [Ministero della Salute](http://www.dati.salute.gov.it/). Data of particulate 2.5 (2017) comes from the [Istituto Superiore Per La protezione Ambientale](https://annuario.isprambiente.it/pon/basic/14).

The documentation of the functions reports and describes each variable (`colnames`) and list data sources. Because of the large amount of variables, to facilitate exploration of the documentation, it was deemed more practical to create separate functions with separate documentation for each of the country, instead of creating a single function with an argument relative to the country.

  
#  Implementation

Examples of use


# Discussion




<!-- rmarkdown::render("/Users/heverz/Documents/R_projects/covid19census/vignettes/draft/draft.Rmd", output_file= "draft.pdf") -->

<!-- An equation with a label for cross-referencing: -->

<!-- \begin{equation}\label{eq:eq1} -->
<!-- \int^{r_2}_0 F(r,\varphi){\rm d}r\,{\rm d}\varphi = [\sigma r_2/(2\mu_0)] -->
<!-- \int^{\infty}_0\exp(-\lambda|z_j-z_i|)\lambda^{-1}J_1 (\lambda r_2)J_0 -->
<!-- (\lambda r_i\,\lambda {\rm d}\lambda) -->
<!-- \end{equation} -->

<!-- This equation can be referenced as follows: Eq. \ref{eq:eq1} -->

<!-- ## A subsection -->

<!-- A numbered list: -->

<!-- 1) First point -->
<!-- 2) Second point -->
<!--     - Subpoint -->

<!-- A bullet list: -->

<!-- * First point -->
<!-- * Second point -->

<!-- # Results -->

<!-- Generate a figure. -->

<!-- ```{r fig1, fig.cap="This is the first figure.",echo=TRUE} -->
<!-- plot(1:10,main="Some data",xlab="Distance (cm)",ylab="Time (hours)") -->
<!-- ``` -->

<!-- You can reference this figure as follows: Fig. \ref{fig:fig1}. -->

<!-- # ```{r fig2, fig.cap="This is the second figure.",echo=TRUE} -->
<!-- # plot(1:5,pch=19,main="Some data",xlab="Distance (cm)",ylab="Time (hours)") -->
<!-- # ``` -->
<!-- #  -->
<!-- # Reference to second figure: Fig. \ref{fig:fig2} -->
<!-- #  -->
<!-- <!-- # Generate a table. --> -->

<!-- ```{r tab1, results="asis", echo=TRUE} -->
<!-- df = data.frame(ID=1:3,code=letters[1:3]) -->
<!-- print(xtable(df,caption="This is the table caption",label="tab:tab1"), -->
<!--       comment=FALSE) -->
<!-- <!-- ``` --> -->

<!-- You can reference this table as follows: Table \ref{tab:tab1}. -->

<!-- # Discussion -->

<!-- You can cross-reference sections and subsections as follows: Section \ref{materials-and-methods} and Section \ref{a-subsection}. -->

<!-- ***Note:*** the last section in the document will be used as the section title for the bibliography. -->

# References
