---
title: "Intersection COVID-19: Explore data"
date: "`r Sys.time()`"
categories:
  - covid-19
lastmod: "`r Sys.time()`"
keywords: []
description: ''
output:
  html_document:
    df_print: kable
    toc: true
    theme: journal
---



# Italy Descriptive Table


```{r library_data}
path_scripts <- ("scripts/")


source(paste0(path_scripts, "libraries_functions.R"))
```

## flu

```{r}

new_order_it <- c("n", "deaths", "case_ratio"," pop_km2", "lat", "perc_chronic_diab", "perc_chronic_bronc", "perc_chronic_hyp", "perc_chronic_heart" ) 


data_it <- getit_all()

today_it <- 
  data_it %>% 
    filter(date == max(date)) 

tab_it_flu <- 
  today_it %>% 
  filter(date == max(date)) %>% 
  select(region, deaths, cases, lat, perc_imm65, pop_km2, perc_chronic_diab,
         perc_chronic_bronc, perc_chronic_hyp, perc_chronic_heart, pop_tot) %>% 
  mutate_if(is.numeric, round, 3) %>% 
  # 53 is median value
  mutate(perc_imm65= if_else(perc_imm65 > 53.00000, "high53", "low53")) %>% 
  mutate( deaths = deaths / pop_tot * 100000,
          case_ratio = cases / pop_tot * 100000
          ) %>% 
  group_by(perc_imm65) %>% 
  mutate(n = n()) %>% 
  summarise_if(is.numeric, funs(mean, sd)) %>% 
  pivot_longer(-perc_imm65) %>% 
  separate(name, c("var", "metric"), "_(?=(mean)|(sd))") %>% 
  unite(perc_imm65, perc_imm65, metric) %>% 
  pivot_wider(names_from = perc_imm65, values_from = value) %>% 
  mutate_if(is.numeric, round,1)  %>% 
  mutate(
     "<53% (St.Dev.)"= paste(low53_mean,"(", low53_sd, ")"),
     ">53% (St.Dev.)"= paste(high53_mean,"(",high53_sd, ")")) %>% 
  select(var, "<53% (St.Dev.)", ">53% (St.Dev.)") %>% 
  filter(!var %in% c("pop_tot", "perc_imm65", "cases"))%>%
  arrange(match(var, !!new_order_it)) %>% 
  mutate(var = recode(var,
    "n" = "Number of counties",
    "deaths" = "COVID-19 death rate (per 100,000 people)",
    "case_ratio" = "COVID-19 confirmed-case rate (per 100,000 people)",
    "lat" = "Latitude",
    "chronic_heart" = "% chronic heart disease",
    "chronic_diab" = "% chronic diabetes",
    "chronic_bronc" =  "% chronic bronchitis",
    "chronic_hyp" = "% chronic hypertension",
    "pop_km2" = "Population density (people per squared km)"
    ))

```

## tot

```{r}
tab_it_tot <- 
  today_it %>% 
  select(region, deaths, cases, lat, perc_imm65, pop_km2, perc_chronic_diab,
         perc_chronic_bronc, perc_chronic_hyp, perc_chronic_heart, pop_tot) %>% 
  mutate_if(is.numeric, round, 1) %>% 
  # 53 is median value
  mutate( deaths = deaths/pop_tot * 100000,
          case_ratio = cases / pop_tot * 100000,
          all_d = "all") %>% 
  group_by(all_d) %>% 
  mutate(n = n()) %>% 
  summarise_if(is.numeric, funs(mean, sd)) %>% 
  pivot_longer(-all_d) %>% 
  separate(name, c("var", "metric"), "_(?=(mean)|(sd))") %>% 
  unite(all_d, all_d, metric ) %>% 
  pivot_wider(names_from = all_d, values_from = value) %>% 
  mutate_if(is.numeric, round, 1)  %>% 
  
  mutate(
     "All (St.Dev.)" = paste(all_mean,"(", all_sd, ")")) %>% 
  select(var, "All (St.Dev.)") %>% 
  filter(!var %in% c("pop_tot", "imm65", "total_cases"))%>%
  arrange(match(var, !!new_order_it)) %>% 
  mutate(var = recode(var,
    "n" = "Number of counties",
    "deaths" = "COVID-19 death rate (per 100,000 people)",
     "case_ratio" = "COVID-19 confirmed-case rate (per 100,000 people)",
    "lat" = "Latitude",
    "chronic_heart" = "% chronic heart disease",
    "chronic_diab" = "% chronic diabetes",
    "chronic_bronc" =  "% chronic bronchitis",
    "chronic_hyp" = "% chronic hypertension",
    "pop_km2" = "Population density (people per squared km)"
    ))

  
tab_it_all <- inner_join(tab_it_tot, tab_it_flu, by = "var")



print(
  xtable(
    tab_it_all
  ),
  include.rownames=FALSE,
  comment = FALSE,
  align = rep("c", ncol(tab_it))
)
```

# US Descriptive Table


```{r us_scripts, warning=FALSE}
# path_scripts <- ("scripts/")
# us_scripts <- list(
#   "libraries_functions.R",
#   "us_preprocess.R"
#   # ,
#   # "us_analysis.R"
# )
# 
lapply(us_scripts, function(x) source(paste0(path_scripts, x)))

library(kableExtra)

```





```{r}
new_order <- c(
  #5: COVID-19
  "n",
  "death_rate",
  "case_ratio",
  "XX_days_f0",
  
  #5: Socioeconomic factors
  "XX_perc_families",
  "XX_perc_family_only_onep",
  "XX_perc_edu_bachelor",
  "XX_perc_withinternet",
  "XX_median_income",
  
  #19 Health factors
  "XX_ratio_beds",
  "XX_perc_alzheimer_dementia",
  "XX_perc_asthma",
  "XX_perc_atrial_fibrillation",
  "XX_perc_cancer_breast",
  "XX_perc_cancer_colorectal",
  "XX_perc_cancer_lung",
  "XX_perc_ch_obstructive_pulm",
  "XX_perc_chronic_kidney_disease",
  "XX_perc_depression",
  "XX_perc_diabetes",
  "XX_perc_heart_failure",
  "XX_perc_hypertension",
  "XX_perc_ischemic_heart_disease",
  "XX_perc_obesity",
  "XX_perc_osteoporosis",
  "XX_perc_rheumatoid_arthritis",
  "XX_perc_stroke",
  "XX_perc_tobacco_use",

  #5: Environmental factors
  "XX_pm2.5",
  "XX_summer_temp",
  "XX_summer_hum",
  "XX_winter_temp",
  "XX_winter_hum",
  
  #4 Population demographics
  "XX_median_age",
  "XX_perc_age65_over",
  "XX_sex_ratio",
  "XX_child_dependency",
  
  #7 Race
  "XX_perc_black",
  "XX_perc_lat",
  "XX_perc_white",
  "XX_perc_asian",
  "XX_perc_island",
  "XX_perc_other",
  "XX_perc_two_more_races"
)
```

## flu
```{r}
today_filt <-   today_us %>% 
  # THIS IMPORTANT
   filter(NC_cases >= 10) 

median(today_filt$ZZ_perc_imm65)


tab_us_flu <-
  today_us %>% 
  # THIS IMPORTANT
   filter(NC_cases >= 10) %>% 
   mutate(median = median(ZZ_perc_imm65)) %>% 
   select(matches("ZZ|XX|YY|NP|NC")) %>% 
   select(
     -logitZZ_perc_imm65,
     -XX_total_tests,
     -XX_total_beds,
     
     ) %>% 
   mutate_at(vars(matches("perc")), ~ . * 100) %>%
   mutate(ZZ_perc_imm65 = if_else(ZZ_perc_imm65 > 45, "high45", "low45")) %>%
  
   mutate(
     death_rate = YY_deaths / NP_total_pop * 100000,
     case_ratio = NC_cases / NP_total_pop * 100000,
     XX_ratio_beds = XX_ratio_beds * 1000,
     XX_median_income	= XX_median_income / 1000
     ) %>%  
  
   group_by(ZZ_perc_imm65) %>% 
   mutate(n = n()) %>% 
   summarize_if(is.numeric, funs(mean, sd)) %>% 
   
   pivot_longer(-ZZ_perc_imm65) %>% 
   separate(name, c("var", "metric"), "_(?=(mean)|(sd))") %>% 
   unite(imm65, ZZ_perc_imm65, metric ) %>% 

   pivot_wider(names_from = imm65, values_from = value) %>% 
   mutate_if(is.numeric, round,1)  %>% 
   mutate(
     "\u226445% (St.Dev.)"= paste(low45_mean,"(", low45_sd, ")"),
     ">45% (St.Dev.)"= paste(high45_mean,"(", high45_sd, ")")) %>% 
  select(var, "\u226445% (St.Dev.)", ">45% (St.Dev.)") %>%
  filter(!var %in% c("NP_total_pop", "YY_deaths", "NC_cases")) %>% 
  arrange(match(var, !!new_order)) %>% 
  rename(Variable = var) %>% 
  mutate(Variable = recode(Variable,
    "n" = "Number of counties",
    
    "death_rate" = "COVID-19 death rate (per 100,000 people)",
    "case_ratio" = "COVID-19 confirmed-case rate (per 100,000 people)",
    "XX_days_f0" =  "Number of days since first case",
    
    "XX_perc_families" = "% families",
    "XX_perc_family_only_onep" = "% families with only one parent",
    "XX_perc_edu_bachelor" =   "% with bachelor",
    "XX_perc_withinternet" = "% with Internet",
    "XX_median_income" = "% median income ($1,000)",
    
    
    "XX_ratio_beds" = "Rate of hospital beds (per 1,000 people)",
    "XX_perc_alzheimer_dementia" = "% with Alzheimer's disease",
    "XX_perc_asthma" = "% with asthma",
    "XX_perc_atrial_fibrillation" = "% with atrial fibrillation",
    "XX_perc_cancer_breast" = "% with breast cancer",
    "XX_perc_cancer_colorectal" = "% with colorectal cancer",
    "XX_perc_cancer_lung" = "% with lung cancer",
    "XX_perc_ch_obstructive_pulm" = "% with obstructive pulmonary disease",
    "XX_perc_chronic_kidney_disease" = "% with chronic kidney disease",
    "XX_perc_depression" = "% with depression",
    "XX_perc_diabetes" = "% with diabetes",
    "XX_perc_heart_failure" = "% with heart failure",
    "XX_perc_hypertension" = "% with hypertension",
    "XX_perc_ischemic_heart_disease" = "% with ischemic heart disease",
    "XX_perc_obesity" = "% with obesity",
    "XX_perc_rheumatoid_arthritis" = "% with rheumatoid arthritis", 
    "XX_perc_stroke" = "% stroke transient ischemic attack",
    "XX_perc_tobacco_use" =  "% using tobacco",

    "XX_pm2.5" = "% average PM2.5(microg/m3)",
    "XX_summer_temp" = "Summer temperature (K)",
    "XX_summer_hum" =  "% summer humidity",
    "XX_winter_temp" = "Winter temperature (K)",
    "XX_winter_hum" = "% winter humidity",
    "XX_median_age" = "% median age",
    
    "XX_perc_age65_over" = "% 65 years or more of age",
    "XX_sex_ratio" = "Sex ratio",
    "XX_child_dependency" = "Child dependency ratio",
    
    "XX_perc_black" =   "% black",
    "XX_perc_lat" =  "% latino",
    "XX_perc_white" = "% white",
    "XX_perc_asian" = "% asian",
    "XX_perc_island" = "% island native",
    "XX_perc_other" =   "% other",
    "XX_perc_two_more_races" = "% two more races"
    
  )
  )

# total test need to be added after
```

## tot

```{r us_descriptive}

tab_us_tot <-
  today_us %>% 
  # THIS IMPORTANT
  filter(NC_cases >= 10) %>% 
   mutate(median = median(ZZ_perc_imm65)) %>% 
   select(matches("ZZ|XX|YY|NP|NC")) %>% 
   select(
     -logitZZ_perc_imm65,
     -XX_total_tests,
     -XX_total_tests,
     -XX_total_beds
     
     ) %>% 
   mutate_at(vars(matches("perc")), ~ . * 100) %>% 
   mutate(ZZ_perc_imm65 = if_else(ZZ_perc_imm65 > 45, "high45", "low45")) %>%  
  
   mutate(
     death_rate = YY_deaths / NP_total_pop * 100000,
     case_ratio = NC_cases / NP_total_pop * 100000,
     # XX_urban = XX_urban * 100,
     XX_ratio_beds = XX_ratio_beds * 1000,
     XX_median_income	= XX_median_income / 1000,
     all_d = "all_d"
     ) %>%  
  
   group_by(all_d) %>% 
   mutate(n = n()) %>% 
   summarize_if(is.numeric, funs(mean, sd)) %>% 
   
   pivot_longer(-all_d) %>% 
   separate(name, c("var", "metric"), "_(?=(mean)|(sd))") %>% 
   unite(all_d, all_d, metric ) %>% 
   pivot_wider(names_from = all_d, values_from = value) %>% 
    mutate_if(is.numeric, round, 1)  %>%
  mutate(
     "All (St.Dev.)" = paste(all_d_mean,"(", all_d_sd, ")")) %>% 
  select(var, "All (St.Dev.)") %>% 
  mutate_if(is.numeric, round, 1)  %>% 
  filter(!var %in% c("NP_total_pop", "YY_deaths", "NC_cases")) %>% 
  arrange(match(var, !!new_order)) %>% 
  rename(Variable = var) %>% 
  mutate(Variable = recode(Variable,
    "n" = "Number of counties",
    
    "death_rate" = "COVID-19 death rate (per 100,000 people)",
    "case_ratio" = "COVID-19 confirmed-case rate (per 100,000 people)",
    "XX_days_f0" =  "Number of days since first case",
    
    "XX_perc_families" = "% families",
    "XX_perc_family_only_onep" = "% families with only one parent",
    "XX_perc_edu_bachelor" =   "% with bachelor",
    "XX_perc_withinternet" = "% with Internet",
    "XX_median_income" = "% median income ($1,000)",
    
    
    "XX_ratio_beds" = "Rate of hospital beds (per 1,000 people)",
    "XX_perc_alzheimer_dementia" = "% with Alzheimer's disease",
    "XX_perc_asthma" = "% with asthma",
    "XX_perc_atrial_fibrillation" = "% with atrial fibrillation",
    "XX_perc_cancer_breast" = "% with breast cancer",
    "XX_perc_cancer_colorectal" = "% with colorectal cancer",
    "XX_perc_cancer_lung" = "% with lung cancer",
    "XX_perc_ch_obstructive_pulm" = "% with obstructive pulmonary disease",
    "XX_perc_chronic_kidney_disease" = "% with chronic kidney disease",
    "XX_perc_depression" = "% with depression",
    "XX_perc_diabetes" = "% with diabetes",
    "XX_perc_heart_failure" = "% with heart failure",
    "XX_perc_hypertension" = "% with hypertension",
    "XX_perc_ischemic_heart_disease" = "% with ischemic heart disease",
    "XX_perc_obesity" = "% with obesity",
    "XX_perc_rheumatoid_arthritis" = "% with rheumatoid arthritis", 
    "XX_perc_stroke" = "% stroke transient ischemic attack",
    "XX_perc_tobacco_use" =  "% using tobacco",

    "XX_pm2.5" = "% average PM2.5(microg/m3)",
    "XX_summer_temp" = "Summer temperature (K)",
    "XX_summer_hum" =  "% Summer humidity",
    "XX_winter_temp" = "Winter temperature (K)",
    "XX_winter_hum" = "% Winter humidity",
    "XX_median_age" = "% median age",
    
    "XX_perc_age65_over" = "% 65 years or more of age",
    "XX_sex_ratio" = "Sex ratio",
    "XX_child_dependency" = "Child dependency ratio",
    
    "XX_perc_black" =   "% black",
    "XX_perc_lat" =  "% latino",
    "XX_perc_white" = "% white",
    "XX_perc_asian" = "% asian",
    "XX_perc_island" = "% island native",
    "XX_perc_other" =   "% other",
    "XX_perc_two_more_races" = "% two more races"

    
  )
  )

tab_us_all <- inner_join(tab_us_tot, tab_us_flu, by = "Variable")

tab_us_clean <- tab_us_all %>% 
  mutate( Category = 
    c( "",
      rep("COVID-19", 3),
       rep("Socioeconomic factors", 5),
       rep("Health factors", 18),
       rep("Environmental factors", 5),
       rep("Population demographics", 4),
       rep("Race", 7)
    )
) %>% 
  tibble() %>% 
  relocate(Category, .before =  Variable) %>% 
  rename(All = "All (St.Dev.)", `≤Median` ="≤45% (St.Dev.)", `>Median` = ">45% (St.Dev.)"  )
  


first_row <- sub("\\s\\(\\s0\\s\\)","", tab_us_clean[1, ])
names(first_row) <- names(tab_us_clean)

tab_us_clean <- tab_us_clean %>% 
  filter(Variable != "Number of counties") 

tab_us_clean <- bind_rows(first_row, tab_us_clean)


kable(tab_us_clean, "latex", longtable = T, booktabs = T) %>%  
  add_header_above(c(" ", " ", "Vaccination Coverage" = 3), bold = TRUE) %>%
  column_spec(1, bold = TRUE) %>%
  row_spec(0, bold = TRUE) %>% 
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") 
```



# #####################

# Some figures US


```{r us_ggcorr, fig.width=12, fig.height=12}
library(ggcorrplot)
M <-   
  today_us %>% 
  select_if(is.numeric) %>% 
  cor( use ="pairwise.complete.obs")
ggcorrplot(M,
           hc.order = TRUE
           # pch.cex = 30,
           # tl.cex = 30
)
```

# Rural -OUTDATED

```{r us_imm_state_rural, fig.width=4, fig.height=12, message=FALSE, warning=FALSE}
library(ggridges)

ordered_levels <-   
  today_us %>% 
  group_by(state) %>% 
  mutate(mean_z = mean(ZZ_perc_imm65)) %>%
  arrange(mean_z) %>% 
  ungroup() %>%
  select(state) %>% 
  unique() %>% 
  unlist()
   
today_us %>% 
  mutate(state = factor(state, levels = ordered_levels)) %>% 
  mutate(urban = factor(recode(XX_urban,
                        `0` = "rural",
                         `1` = "urban"
                        ))
         ) %>% 
        
  ggplot(aes(ZZ_perc_imm65, state, fill = urban)) +
      geom_density_ridges2(alpha = 0.5, scale = 1.1) +
      labs(x = "influenza vaccination in 65 and older (percent)",
           y = NULL
           ) +
  theme(legend.title = element_blank(),
        legend.position="top")
```


```{r us_imm_rural}
today_us %>% 
  mutate(state = factor(state, levels = ordered_levels)) %>% 
  mutate(urban = factor(recode(XX_urban,
                        `0` = "rural",
                         `1` = "urban"
                        ))
         ) %>% 
        
  ggplot(aes(ZZ_perc_imm65, fill = urban)) +
      geom_density(alpha = 0.5) +
      labs(x = "influenza vaccination in age 65 and older (percent)",
           y = NULL
           ) +
      scale_x_continuous(labels = scales::percent) +
      
  theme(legend.title = element_blank(),
        legend.position="top")
```

```{r us_cases_rural}
today_us %>% 
  mutate(state = factor(state, levels = ordered_levels)) %>% 
  mutate(urban = factor(recode(XX_urban,
                        `0` = "rural",
                         `1` = "urban"
                        ))
         ) %>% 
        
  ggplot(aes(log(NC_cases), fill = urban)) +
      geom_density(alpha = 0.5) +
      labs(x = "number of confirmed cases (log2)",
           y = NULL
           ) +
  theme(legend.title = element_blank(),
        legend.position="top")
```




```{r us_deaths, fig.width=4, fig.height=12, message=FALSE, warning=FALSE}
ordered_levels <-   
  today_us %>% 
  group_by(state) %>% 
  mutate(mean_z = mean(YY_deaths)) %>%
  arrange(mean_z) %>% 
  ungroup() %>%
  select(state) %>% 
  unique() %>% 
  unlist()

today_us %>% 
  mutate(state = factor(state, levels = ordered_levels)) %>% 
  mutate(state = factor(state, levels = ordered_levels)) %>% 
  mutate(urban = factor(recode(XX_urban,
                        `0` = "rural",
                        `1` = "urban"
                        ))) %>% 
  
  ggplot(aes(log10(YY_deaths), state, col = urban)) +
      geom_jitter(alpha = 0.5) +
      labs(x = "number of deaths (log2)") +
     theme(legend.title = element_blank(),
           legend.position="top") 


# today_us %>% 
#   filter(YY_deaths > 15000)
```

# Deaths

```{r us_deaths2}
today_us %>% 
   ungroup() %>% 
   group_by(state) %>% 
   summarize(deaths  = sum(YY_deaths)) %>% 

   
   ggplot(aes(reorder(state, deaths), deaths)) +
     geom_col() +
     scale_x_discrete(guide = guide_axis(check.overlap = TRUE, angle = 45)) +
     labs(y = NULL)
    
```



```{r us_perc_state}
today_us %>% 
   group_by(date) %>% 
   mutate(tot = sum(YY_deaths)) %>% 
   group_by(state) %>%
   summarize(perc_death = round((sum(YY_deaths)/first(tot) * 100), 2)) %>% 
   arrange(desc(perc_death))
```

```{r us_perc_case_state}
today_us %>% 
   group_by(date) %>% 
   mutate(tot = sum(NC_cases)) %>% 
   group_by(state) %>%
   summarize(perc_cases = round((sum(NC_cases)/first(tot) * 100),2)) %>% 
   arrange(desc(perc_cases))
```





```{r us_cases_state}
options(scipen = 999)
today_us %>% 
   ungroup() %>% 
   group_by(state) %>% 
   summarize(cases  = sum(NC_cases)) %>% 
   
   ggplot(aes(reorder(state, cases), cases)) +
     geom_col() +
     scale_x_discrete(guide = guide_axis(check.overlap = TRUE, angle = 45)) +
    labs(y = NULL)
    
```



```{r u_age_by_state}
today_us %>% 
  filter(date == max(date)) %>% 
  ggplot(aes(state, XX_perc_age65_over)) +
      geom_boxplot() +
      scale_x_discrete(guide = guide_axis(check.overlap = TRUE, angle = 45)) 
```

```{r us_urban_pop}
# Is urban defined by pop size?
today_us %>% 
  mutate(XX_urban = factor(recode(XX_urban,
                        `0` = "rural",
                        `1` = "urban"
                        ))) %>% 
  ggplot(aes(XX_urban, NP_total_pop/1000, col = XX_urban)) +
    geom_jitter() +

   labs(y = " Population in thousands",
        x = NULL) +
  theme(legend.title = element_blank())


```


# Lord of the Rings




```{r}

path_f <- "/Users/heverz/Dropbox (MechPred)/COVID19/Interference/figs/IT/no_log"

to_plot <- today_it_all %>% 
  select(where(is.numeric)) %>% 
  names()
# 
lord_rings(dat = dat_it_cl, "YY_deaths", model_dat = TRUE, nation = "it")


lapply(to_plot, lord_rings,
       today_it_all,
       model_dat = FALSE,
       log_v = FALSE,
       nation = "it",
       path_f
       
       )

today_it_all %>% 
  ggplot(aes(deaths, region)) +
    geom_col() 

```




```{r}
path_f = "/Users/heverz/Dropbox (MechPred)/COVID19/Interference/figs/US/model/nolog"

names(today_us) <- stringr::str_replace(names(today_us), "-", "_")

numeric_vars <- today_us %>% 
  select(where(is.numeric)) %>% 
  names()

lapply(numeric_vars, lord_rings,
       today_us,
       TRUE,
       FALSE, #log
       path_f 
)

dput(names(today_us))

```



# NYT vs JHU

```{r}
jhu <- getus_all(repo = "jhu") %>% 
    filter(date == max(date))

nyt <- getus_all(repo = "nyt") %>% 
   filter(date == max(date))


sum(unique(nyt$fips)) - sum(unique(jhu$fips))

j_data <- inner_join(jhu, nyt, by = "fips", suffix = c("_jhu", "_nyt") )

j_data_s <- 
  j_data %>% 
  select( matches("date|county|state|fips|cases|deaths")) %>% 
  mutate(case_diff = cases_jhu - cases_nyt, deaths_diff = deaths_jhu - deaths_nyt)


j_data_s %>% 
  ggplot(aes(fips, deaths_diff)) +
    geom_line()
```


```{r}
j_data_s %>% 
  ggplot(aes(fips, case_diff)) +
    geom_line()
```


```{r fig.height=10, fig.width=5}

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


library(plotly)
x <- j_data_s %>% 
  filter(deaths_diff != 0) %>% 
  ggplot(aes( case_diff, state_jhu, col = state_jhu, fips = fips), county_jhu = county_jhu, county_nyt = county_nyt) +
    geom_jitter() +
    theme(legend.position = "none") +
  labs(x = "JHU deaths - NYT deaths",
       y = NULL)

p <- ggplotly(x, width = 500, height = 800, tooltip = c("deaths_diff",
                                                   "fips",
                                                   "county_jhu",
                                                   "state_jhu"
                                                   
                                                   
                                                   )) %>% 
  config(p = .)

p
htmlwidgets::saveWidget(p, "diff_deaths.html")
```



# Unassigned for JHU

```{r fig.width=5, fig.height=6}
data_freeze == "2020-06-10"

dat_all_jhu <- getus_all()

dat_all_jhu %>% 
  filter(date == !!data_freeze) %>% 
  mutate(county_un = if_else(county == "Unassigned", "unassigned", "assigned")) %>% 
  group_by(state, county_un) %>% 
  summarize(n = n(), deaths = sum(deaths, na.rm = TRUE), .groups = "drop") %>% 
  pivot_wider(id_cols = "state", names_from = "county_un", values_from = "deaths") %>% 
  mutate(perc_unas = unassigned/sum(assigned,unassigned, na.rm = TRUE) * 100) %>% 
  
  ggplot(aes(unassigned, state)) +
    geom_col() +
    labs(y = NULL,
             x = "Deaths not assigned to a County (JHU repository)")
  
```


# Ny State Counties


```{r fig.height=6, fig.width=4}
today_us_filt %>% 
  filter(state == "New York") %>% 
  
  ggplot(aes(YY_deaths, reorder(county, YY_deaths))) +
    geom_col()
      
```

# Explore quintiles

```{r}
# again we select the names that start we XX
XX <- grep("XX", names(all_dat), value = TRUE)
# we don't include total beds because we have the bed X population already in
XX <- XX[!XX %in% c("XX_total_beds")]

# formula for propensity score
form_ps <- reformulate(termlabels = XX, response = "logitZZ_perc_imm65")

PropScores_dat <- lm(form_ps, data = today_us_filt)

# dat quint.
dat_quint_split <- 
  today_us_filt %>% 
  mutate(PP = as.factor(ntile(fitted.values(PropScores_dat), 5)),
         PP_cont = fitted.values(PropScores_dat)
         )

print(dat_quint_split , width = 100)
  

```

```{r}

path_f <- "/Users/heverz/Dropbox (MechPred)/COVID19/Interference/figs/US_quint/log"

to_plot <- dat_quint_split %>% 
  select(where(is.numeric)) %>% 
  names()


lapply(
      to_plot,
      fifth_element,
      dat = dat_quint_split,
      log_v = TRUE,
      path_f
       )
```



```{r}
dat_quint_split %>% 
  filter(state == "New York") %>% 
  select(PP) %>% 
  summary()
```




















