---
title: "R Notebook"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r}
library(kableExtra)
```

\begin{longtable}{>{\bfseries}lllll}
\toprule
\multicolumn{1}{c}{\textbf{ }} & \multicolumn{1}{c}{\textbf{ }} & \multicolumn{3}{c}{\textbf{Vaccination Coverage}} \\
\cmidrule(l{3pt}r{3pt}){3-5}
\textbf{Category} & \textbf{Variable} & \textbf{All} & \textbf{≤Median} & \textbf{>Median}\\
\midrule
 & Number of counties & 2163 & 1162 & \vphantom{1} 1001\\

\multirow{-2}{*}{\raggedright\arraybackslash } & Number of counties & 2163 & 1162 & 1001\\
\cmidrule{1-5}
 & COVID-19 death rate (per 100,000 people) & 20.9 ( 44.8 ) & 19.1 ( 34.5 ) & 22.9 ( 54.3 )\\

 & COVID-19 confirmed-case rate (per 100,000 people) & 582.2 ( 803.7 ) & 566.6 ( 692.4 ) & 600.4 ( 916 )\\

\multirow{-3}{*}{\raggedright\arraybackslash COVID-19} & Number of days since first case & 95.7 ( 12.3 ) & 92.9 ( 13 ) & 99 ( 10.4 )\\
\cmidrule{1-5}
 & \% families & 66.5 ( 5.2 ) & 66.9 ( 4.8 ) & 66.1 ( 5.6 )\\

 & \% families with only one parent & 16.4 ( 4.5 ) & 17.4 ( 5 ) & 15.3 ( 3.5 )\\

 & \% with bachelor & 14.5 ( 5.8 ) & 12.1 ( 4.2 ) & 17.3 ( 6.2 )\\

 & \% with Internet & 74 ( 9.1 ) & 70.6 ( 8.9 ) & 77.9 ( 7.6 )\\

\multirow{-5}{*}{\raggedright\arraybackslash Socioeconomic factors} & \% median income (\$1,000) & 52.5 ( 14 ) & 47.4 ( 10.8 ) & 58.5 ( 14.9 )\\
\cmidrule{1-5}
 & Rate of hospital beds (per 1,000 people) & 3.2 ( 3.2 ) & 3.2 ( 3.2 ) & 3.2 ( 3.2 )\\

 & \% with Alzheimer's disease & 10.4 ( 1.9 ) & 10.4 ( 2.1 ) & 10.3 ( 1.6 )\\

 & \% with asthma & 4.6 ( 1.2 ) & 4.4 ( 1.2 ) & 4.8 ( 1.1 )\\

 & \% with atrial fibrillation & 8.2 ( 1.4 ) & 7.8 ( 1.4 ) & 8.7 ( 1.2 )\\

 & \% with breast cancer & 2.8 ( 0.6 ) & 2.6 ( 0.6 ) & 3 ( 0.6 )\\

 & \% with colorectal cancer & 1.1 ( 0.3 ) & 1.1 ( 0.4 ) & 1.1 ( 0.3 )\\

 & \% with lung cancer & 1 ( 0.3 ) & 1 ( 0.3 ) & 1 ( 0.2 )\\

 & \% with obstructive pulmonary disease & 13 ( 3.5 ) & 13.6 ( 3.7 ) & 12.2 ( 3.1 )\\

 & \% with chronic kidney disease & 23.5 ( 4.2 ) & 23.8 ( 4.5 ) & 23.1 ( 3.7 )\\

 & \% with depression & 18 ( 3.3 ) & 17.5 ( 3.4 ) & 18.6 ( 3 )\\

 & \% with diabetes & 27.4 ( 4.7 ) & 28.5 ( 4.8 ) & 26.1 ( 4.2 )\\

 & \% with heart failure & 14.5 ( 3 ) & 15.2 ( 3.2 ) & 13.7 ( 2.6 )\\

 & \% with hypertension & 57.7 ( 8.1 ) & 58.5 ( 8.6 ) & 56.9 ( 7.3 )\\

 & \% with ischemic heart disease & 27.3 ( 5.2 ) & 28 ( 5.5 ) & 26.4 ( 4.7 )\\

 & \% with obesity & 17.5 ( 5.6 ) & 17.8 ( 6 ) & 17.2 ( 5.2 )\\

 & \% with rheumatoid arthritis & 33.6 ( 4.8 ) & 34.1 ( 5.2 ) & 32.9 ( 4.3 )\\

 & \% stroke transient ischemic attack & 3.6 ( 0.9 ) & 3.6 ( 1 ) & 3.5 ( 0.8 )\\

\multirow{-18}{*}{\raggedright\arraybackslash Health factors} & \% using tobacco & 9.6 ( 3.1 ) & 10.1 ( 3.3 ) & 9.1 ( 2.8 )\\
\cmidrule{1-5}
 & \% average PM2.5(microg/m3) & 8.9 ( 2.3 ) & 8.6 ( 2.4 ) & 9.2 ( 2.2 )\\

 & Summer temperature (K) & 303.2 ( 3.1 ) & 303.9 ( 3.2 ) & 302.3 ( 2.9 )\\

 & \% Summer humidity & 89.6 ( 9.2 ) & 89.3 ( 10.6 ) & 89.9 ( 7.3 )\\

 & Winter temperature (K) & 280.8 ( 6.7 ) & 282.5 ( 6.8 ) & 278.8 ( 6 )\\

\multirow{-5}{*}{\raggedright\arraybackslash Environmental factors} & \% Winter humidity & 87.4 ( 4.9 ) & 87.6 ( 5.1 ) & 87.2 ( 4.6 )\\
\cmidrule{1-5}
 & \% median age & 40.2 ( 4.8 ) & 40.3 ( 4.9 ) & 40.1 ( 4.8 )\\

 & \% 65 years or more of age & 17.5 ( 4.1 ) & 17.7 ( 4 ) & 17.2 ( 4.1 )\\

 & Sex ratio & 99.5 ( 9 ) & 100.9 ( 11.1 ) & 97.8 ( 5.1 )\\

\multirow{-4}{*}{\raggedright\arraybackslash Population demographics} & Child dependency ratio & 37.9 ( 6.1 ) & 38.9 ( 6.4 ) & 36.8 ( 5.5 )\\
\cmidrule{1-5}
 & \% black & 10.4 ( 15.1 ) & 12.6 ( 18 ) & 7.8 ( 10.1 )\\

 & \% latino & 9.9 ( 13.7 ) & 11.6 ( 16.9 ) & 7.9 ( 8.3 )\\

 & \% white & 81.9 ( 16.2 ) & 79.7 ( 18.8 ) & 84.4 ( 12.2 )\\

 & \% asian & 1.6 ( 2.6 ) & 1.1 ( 2.1 ) & 2.2 ( 3.1 )\\

 & \% island native & 0.1 ( 0.2 ) & 0.1 ( 0.1 ) & 0.1 ( 0.2 )\\

 & \% other & 2.2 ( 3.5 ) & 2.5 ( 4.2 ) & 2 ( 2.5 )\\

\multirow{-7}{*}{\raggedright\arraybackslash Race} & \% two more races & 2.4 ( 1.7 ) & 2.3 ( 1.7 ) & 2.6 ( 1.6 )\\
\bottomrule
\end{longtable}