---
title: "R Notebook"
output: html_notebook
---

https://www.cdc.gov/nchs/nvss/vsrr/covid19/index.htm?fbclid=IwAR3WB5hhR3DJyage-ORkZfvSI2M32v7m3E2J6-p4R8mVq5zQo-3GNIBpoqo

```{r}
library(tidyverse)
# install.packages("cdccovidview", repos = c("https://cinc.rud.is", "https://cloud.r-project.org/"))
library("cdccovidview")
library(ggplot2)
theme_set(theme_bw())
```


```{r}
dat <- mortality_surveillance_data()

dat <- tibble::tribble(
                ~United.States5, ~`37308`, ~`719438`, ~`97`, ~`64382`, ~`16564`, ~`5846`,
                      "Alabama",     "152",      12426,   91L,       769,      "42",     "83",
                       "Alaska",       "-",        856,   79L,        41,       "-",      "-",
                      "Arizona",     "194",      15859,  101L,      1115,     "102",    "105",
                     "Arkansas",      "32",       7872,   94L,       527,      "10",     "67",
                   "California",   "1224",      69721,   98L,      6029,     "714",    "552",
                     "Colorado",     "551",      10846,  104L,       972,     "328",     "91",
                  "Connecticut",     "120",       1398,   15L,       130,      "34",     "18",
                     "Delaware",      "53",       2034,   85L,       123,      "24",     "14",
         "District of Columbia",      "66",       1464,   92L,       173,      "66",      "-",
                      "Florida",     "809",      54225,   99L,      3934,     "445",    "282",
                      "Georgia",     "460",      19740,   91L,      1306,     "212",     "94",
                       "Hawaii",       "-",       2830,   94L,       185,       "-",     "18",
                        "Idaho",      "44",       3553,   96L,       195,      "13",     "24",
                     "Illinois",   "1296",      29232,  104L,      2724,     "722",    "171",
                      "Indiana",     "494",      16503,   95L,      1526,     "266",    "121",
                         "Iowa",      "78",       7447,   94L,       531,      "20",     "80",
                       "Kansas",      "89",       6582,   94L,       455,      "40",     "85",
                     "Kentucky",     "117",      10855,   86L,       969,      "67",     "86",
                    "Louisiana",     "920",      11401,   95L,       902,     "400",     "63",
                        "Maine",      "40",       3824,  100L,       318,      "11",     "30",
                     "Maryland",     "710",      13780,  105L,      1256,     "286",    "110",
                "Massachusetts",   "2009",      17802,  112L,      2088,     "735",    "150",
                     "Michigan",   "1851",      26994,  106L,      2657,     "892",    "221",
                    "Minnesota",     "169",      11352,   99L,       832,      "60",    "113",
                  "Mississippi",     "186",       8064,   99L,       737,      "90",     "51",
                     "Missouri",     "196",      15163,   89L,       971,      "68",    "169",
                      "Montana",       "-",       2248,   84L,       132,       "-",     "32",
                     "Nebraska",      "21",       3971,   90L,       306,       "-",     "27",
                       "Nevada",     "134",       6431,   96L,       534,     "106",     "36",
                "New Hampshire",      "56",       3207,   99L,       224,      "18",     "29",
                   "New Jersey",   "5109",      26794,  131L,      4341,   "2546",    "110",
                   "New Mexico",      "36",       4113,   85L,       291,      "22",     "25",
                    "New York6",   "4920",      32144,  122L,      5148,   "2541",    "188",
                "New York City",  "11425",      31247,  219L,      6285,   "4199",    "862",
               "North Carolina",       "0",      10727,   43L,       639,       "0",    "127",
                 "North Dakota",       "-",       1546,   85L,       140,       "-",     "18",
                         "Ohio",     "172",      27169,   82L,      1554,      "74",    "227",
                     "Oklahoma",     "117",       8768,   84L,       782,      "43",     "90",
                       "Oregon",      "77",       8438,   89L,       453,      "34",     "59",
                 "Pennsylvania",   "1385",      28073,   78L,      2164,     "552",    "176",
                 "Rhode Island",      "55",       2235,   82L,       124,      "13",     "23",
               "South Carolina",     "150",      12807,  101L,       786,      "56",     "91",
                 "South Dakota",       "-",       1898,   89L,       149,       "-",     "21",
                    "Tennessee",     "134",      18441,   95L,      1386,      "67",    "119",
                        "Texas",     "446",      49284,   93L,      3669,     "179",    "311",
                         "Utah",      "30",       4697,   96L,       279,      "11",     "39",
                      "Vermont",      "42",       1570,  104L,       108,      "10",     "14",
                     "Virginia",     "351",      17751,   99L,      1000,     "112",    "104",
                   "Washington",     "527",      14141,   95L,      1176,     "281",     "98",
                "West Virginia",      "13",       5048,   85L,       369,       "-",     "57",
                    "Wisconsin",     "209",      13718,  100L,       786,      "32",    "145",
                      "Wyoming",       "-",       1149,   99L,        92,       "-",      "-",
                  "Puerto Rico",      "65",       5201,    0L,       737,      "33",     "28"
         )


names(dat) <- c("state","covid19_tot", "deaths_all", "perc_expect", "pneumonia", "pneumonia_covid19","flu")
```



```{r warning=false}


dat_clean <- dat %>% 
 mutate_at(vars(covid19_tot:flu), as.numeric)

dat_clean[is.na(dat_clean)] <- 0

dat_clean2 <-  
  dat_clean %>% 
 mutate(perc_ratio = pneumonia_covid19/covid19_tot * 100) %>% 
  na.omit()


dat_clean2 %>% 
  ggplot(aes(reorder(state, perc_ratio), perc_ratio)) +
     geom_col(fill = "grey", col = "black") +
     scale_x_discrete(guide = guide_axis(check.overlap = TRUE, angle = 45)) +
    labs(
      title = "Ratio covid19 pneumonia over total covid19",
      x = NULL) 
    
```
 


```{r}
library(covid19census)

dat_us <- getus_all(repo = "jhu")

dat_test <- dat_us %>% 
  filter(date == "2020-05-01") %>% 
  group_by(state) %>% 
  dplyr::summarise(total_pop = sum(total_pop, na.rm = TRUE), pos = first(positive), neg = first(negative), pen = first(pending)) %>%
  group_by(state) %>% 
  mutate( total_test = sum(pos,neg,pen, na.rm = TRUE), test_pop = total_test/total_pop *100)

dat_test %>% 
  ggplot(aes(reorder(state, test_pop), test_pop)) +
     geom_col(fill = "grey", col = "black") +
     scale_x_discrete(guide = guide_axis(check.overlap = TRUE, angle = 45)) +
    labs(
      title = "test per 100 people",
      x = NULL) 
```



```{r}

dat_all <- inner_join(dat_test, dat_clean2, by = "state")

dat_all %>% 
  ggplot(aes(log2(perc_ratio), log2(test_pop)) ) +
    geom_point()
```

```{r}
dat_all2 <- 
  na.omit(dat_all) 
x <- cor.test(log2(dat_all2$perc_ratio), log2(dat_all2$test_pop))

x
```































